# Generated by Django 4.0.6 on 2022-08-31 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='dates',
        ),
    ]
