# Generated by Django 4.0.6 on 2022-08-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_date_todo_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dates',
            field=models.CharField(max_length=100),
        ),
    ]
